# Generated by Django 5.2.7 on 2025-11-05 13:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("heart", "Heart"),
                            ("trending_up", "Trending Up"),
                            ("hand_heart", "Hand Heart"),
                        ],
                        max_length=255,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 6), ("cta", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("cta_primary_text", 0),
                                ("cta_primary_url", 3),
                                ("cta_secondary_text", 4),
                                ("cta_secondary_url", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 3), ("style", 7), ("icon_name", 4)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("excerpt", models.TextField()),
                ("link_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
        ),
    ]
